version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.2
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2
    ports:
      - 8080:8080
      - 8443:8443
    restart: unless-stopped
