version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    command: start-dev
    container_name: keycloak2   
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: h2
    ports:
      - 8080:8080
      - 8443:8443
    restart: always
